---
apiVersion: v1
kind: ConfigMap

metadata:
  name: todo-app
  namespace: kubernetes-dashboard
  labels:
    app: todo-app
data:
  # Configuration values can be set as key-value properties

  NODE_ENV: webapp
  DB_NAME: csye7125
  DB_PASS: Q3N5ZTcyMTUy
  DB_USERNAME: csye7125
  DB_HOST: jdbc:postgresql://rdsdbcsye7125.cny8sxnztedt.us-east-1.rds.amazonaws.com:5432/rdsdbcsye7125