apiVersion: v1
kind: Service
metadata:
  name: todo-app
  namespace: kubernetes-dashboard
  labels:
    app: todo-app
spec:
  type: LoadBalancer
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000